<?php
declare(strict_types=1);
final class SupabaseClient
{
    private $url; private $anonKey; private $accessToken;
    public function __construct(string $url, string $anonKey, ?string $accessToken = null) { $this->url = $url; $this->anonKey = $anonKey; $this->accessToken = $accessToken; }
    public function rest(string $table, string $query = '', string $method = 'GET', $body = null): array { $key = $this->anonKey; return $this->request($this->url . '/rest/v1/' . rawurlencode($table) . ($query ? '?' . $query : ''), $method, $body, ['apikey: ' . $key, 'Authorization: Bearer ' . ($this->accessToken ?: $key), 'Prefer: return=representation']); }
    public function auth(string $path, string $method = 'POST', $body = null): array { return $this->request($this->url . '/auth/v1/' . ltrim($path, '/'), $method, $body, ['apikey: ' . $this->anonKey]); }
    public function storageUpload(string $bucket, string $path, array $file): array { $content = file_get_contents($file['tmp_name']); if ($content === false) throw new RuntimeException('อ่านไฟล์สลิปไม่สำเร็จ'); return $this->request($this->url . '/storage/v1/object/' . rawurlencode($bucket) . '/' . str_replace('%2F', '/', rawurlencode($path)), 'POST', $content, ['apikey: ' . $this->anonKey, 'Authorization: Bearer ' . ($this->accessToken ?: $this->anonKey), 'Content-Type: ' . $file['type'], 'x-upsert: false']); }
    public function storageSignedUrl(string $bucket, string $path, int $expiresIn = 300): string { $response = $this->request($this->url . '/storage/v1/object/sign/' . rawurlencode($bucket) . '/' . str_replace('%2F', '/', rawurlencode($path)), 'POST', ['expiresIn' => $expiresIn], ['apikey: ' . $this->anonKey, 'Authorization: Bearer ' . ($this->accessToken ?: $this->anonKey)]); $signed = $response['signedURL'] ?? $response['signedUrl'] ?? null; if (!is_string($signed) || $signed === '') throw new RuntimeException('สร้างลิงก์สลิปชั่วคราวไม่สำเร็จ'); return strpos($signed, 'http') === 0 ? $signed : $this->url . '/storage/v1' . $signed; }
    private function request(string $url, string $method, $body, array $headers): array { $ch = curl_init($url); if ($ch === false) throw new RuntimeException('Supabase connection could not be initialized'); $headers[] = 'Accept: application/json'; if (is_array($body)) { $body = json_encode($body, JSON_THROW_ON_ERROR); $headers[] = 'Content-Type: application/json'; } curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_CUSTOMREQUEST => $method, CURLOPT_HTTPHEADER => $headers, CURLOPT_POSTFIELDS => $body, CURLOPT_TIMEOUT => 20]); $raw = curl_exec($ch); $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE); $error = curl_error($ch); curl_close($ch); if ($raw === false) throw new RuntimeException('เชื่อมต่อ Supabase ไม่สำเร็จ: ' . $error); $decoded = json_decode($raw, true); if ($status >= 400) throw new RuntimeException((string) ($decoded['msg'] ?? $decoded['message'] ?? $decoded['error_description'] ?? 'Supabase request failed')); return is_array($decoded) ? $decoded : []; }
}
